### ISSUE TITLE
Clarify lowest value of maxMultiplicity of relations

### ISSUE THREAD

**Issue by mlagally** [Azure/opendigitaltwins-dtdl#100]
Please clarify why the lowest value of the max multiplicity of a relationship is 2.
The current text defines maxMultiplicity as:
> must be > 1 and >= min-Multiplicity

**Comment by briancr-ms** [comment]
This looks like a doc bug. A value of 1 for maxMultiplicity is accepted. (Tested with the C# DTDL parser (3.12.5): https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/.)

There are a few other doc bugs. I'll do a doc update soon and fix all of these.
