### ISSUE TITLE
Can't see properties for models with complex types (object)

### ISSUE THREAD

**Issue by sanjaybhagia** [Azure/opendigitaltwins-dtdl#106]
Hi, 
I'm trying to understand how to use the complex types of type 'Object' when defining the dtdl for a model. 

I've the following model:

```json
{
    "@id": "dtmi:mycompany:project:model;1",
    "@type": "Interface",
    "displayName": "TestModel",
    "@context": "dtmi:dtdl:context;2",
    "contents": [
        {
            "@type": "Property",
            "name": "name",
            "schema": "string"
        },
        {
            "@type": "Property",
            "name": "CustomObject",
            "schema": "dtmi:mycompany:project:customobject;1"
        }
    ],
    "schemas": [
        {
            "@id": "dtmi:mycompany:project:customobject;1",
            "@type": "Object",
            "fields": [
                {
                    "name": "x",
                    "schema": "double"
                },
                {
                    "name": "y",
                    "schema": "double"
                }
            ]
        }
    ]
}
```

I upload the model and when I create the twin based on this, I only see name property that I can update. 

![image](https://user-images.githubusercontent.com/4527128/101696138-bd146500-3ac9-11eb-809d-63f4d89283bd.png)

I'm following the schema from this documentation: https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md

Is this the desired behavior? 

I want to set the twin properties so that I can represent custom objects ( Preferably a JSON array but as I understand that's not possible as of now, so trying to understand at least the objects part). 

Appreciate any guidance on this.

**Comment by briancr-ms** [comment]
This looks like a limitation in the ADT Explorer sample. The model you posted is correct. Once you create your digital twin (testtwin), you can update it through the REST API or by using the ADT SDK with a patch body like this:
```
[
  {
    "op": "add",
    "path": "/CustomObject",
    "value": { "x": 1.2, "y": 2.3 }
  }
]
```

Once there's some data in your digital twin, then you can view and edit it in ADT Explorer.

**Comment by sanjaybhagia** [comment]
Thanks briancr-ms, I'll give it a try.

**Comment by sanjaybhagia** [comment]
Spot on Brian! It worked for me.
Thanks
