### ISSUE TITLE
Download All Certified Device JSON Files

### ISSUE THREAD

**Issue by shaggygi** [Azure/opendigitaltwins-dtdl#11]
It would be nice to have a link to download all provided JSON files from the [Certified Device category page](https://catalog.azureiotsolutions.com/alldevices).  This would be helpful for users to quickly get various types of device capabilities so they can 1) review format to become familiar and 2) use content to test their own parsing/generation APIs/tooling.

Understanding we can currently download individual, getting all docs would be even better 😄

**Comment by konichi3** [comment]
Hi Greg,

Thank you very much for your feedback. This is definitely great feedback and provide device catalog users an ability to search the capabilities exposed through interfaces. We will evaluate the feedback internally and loop back if there is an update.

thanks,
Koichi

**Comment by mlagally** [comment]
Perhaps as a short term approach, some additional real world examples in this repo would be very helpful to get a better understanding of the capabilities of the language.

**Comment by askpatrickw** [comment]
This is probably new information since the original posting, but you can see these in the globalRepository.

https://preview.catalog.azureiotsolutions.com/globalRepository/capabilityModels
