### ISSUE TITLE
Semantic type for CO2 concentration

### ISSUE THREAD

**Issue by matsujirushi** [Azure/opendigitaltwins-dtdl#110]
Hi,
I can't find a semantic type for CO2 concentration.
Which one do you think would be best to use?

https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#semantic-types

**Comment by milijan** [comment]
Are you looking for ppm to g/m3 conversion https://www.teesing.com/en/page/library/tools/ppm-mg3-converter ?

**Comment by matsujirushi** [comment]
Hi @milijan ,
Thanks for reply.
Consider changing to g/m3.
