### ISSUE TITLE
DTDL v2 Interface's '@type' property is annotated as an IRI

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/opendigitaltwins-dtdl#112]
In looking at the specification for DTDL v2 the `@type` property on objects is defined in the docs as an IRI, yet the value needs to be "Interface", "Telemetry", etc. which are not a valid IRIs as they do not include schema information. Is this an error? Perhaps I'm missing something.

**Comment by briancr-ms** [comment]
The spec assumes some knowledge of JSON-LD and RDF (there is a separate issue to improve this, #86). The terms "Interface", "Telemetry", etc. are defined in the JSON-LD context (https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/context/DTDL.v2.context.json) and expand to IRIs (such as `dtmi:dtdl:class:Interface;2`).
