### ISSUE TITLE
DTDL v2 validation

### ISSUE THREAD

**Issue by tobilg** [Azure/opendigitaltwins-dtdl#113]
Sorry for maybe asking a newbie question: Are there any plans to provide a JSON schema of the DTDL v2 definition, so that Interface definitions can be formally validated?

**Comment by briancr-ms** [comment]
We provide a DTDL parser (currently only in C#) that provides validation: https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/3.12.5.

DTDL is defined as a set of RDF classes along with constraints. We are looking at publishing the DTDL metamodel (classes + constraints) but aren't quite ready to do this yet.

**Comment by askpatrickw** [comment]
What about using the VSCode DTDL plugin ?
https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-dtdl

**Comment by briancr-ms** [comment]
Yes, the VS Code DTDL extension is great, too!
