### ISSUE TITLE
Documentation issue: Geospatial schema example typo

### ISSUE THREAD

**Issue by bawilless** [Azure/opendigitaltwins-dtdl#115]
In the [Geoapatial schema example documentation](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#geospatial-schema-examples) the telemetry example specifies . . .

    {
        "location": {
            "type": "Point",
            "coordinates": [ 47.643742, -122.128014 ]
        }
    }

The 'P' in "Point" should be lower case, the correct JSON is . . . 

    {
        "location": {
        "type": "point",
        "coordinates": [ 47.643742, -122.128014 ]
        }
    }

**Comment by briancr-ms** [comment]
Thanks for your feedback on this. According to the GeoJSON RFC (https://datatracker.ietf.org/doc/html/rfc7946), the property "type" must be one of the GeoJSON types, which include the case-sensitive strings "Point", "MultiPoint", "LineString", etc. Given the description in the RFC, the correct JSON for the GeoJSON Point example is `"type": "Point"`.
