### ISSUE TITLE
Question: How to understanding `writable`?

### ISSUE THREAD

**Issue by Mrliu8023** [Azure/opendigitaltwins-dtdl#121]
The explain of `writable` is "A boolean value that indicates whether the property is writable by an external source, such as an application, or not. The default value is false (read-only).", I have a confusion about it. Does it mean that need two API for managing twins? One used by twin management web, Another one is used by external source?
Are there any example or practical scenarios?
Looking forward to your answer,thanks~

**Comment by rido-min** [comment]
Hey @Mrliu8023 

The concept of writable properties is mapped to desired/reported properties in DeviceTwins, explained here https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins

There are APIs for device and service side, each of those allows to read/write where apropiate:

- Reported Properties (aka ReadOnly Properties in DTDL) can be updated from the device and read from the service
- Writable Properties (aka Writable Properties in DTDL) can be updated from the service, and pushed as C2D message to devices.

**Comment by Mrliu8023** [comment]
Thanks!
