### ISSUE TITLE
DTDL2 parser library not available as source code

### ISSUE THREAD

**Issue by svenna** [Azure/opendigitaltwins-dtdl#123]
The Microsoft.Azure.DigitalTwins.Parser library available [https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/](https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/) links to the following url
[https://github.com/Azure/azure-iot-digitaltwin-libraries](https://github.com/Azure/azure-iot-digitaltwin-libraries)
but this ends in a 404. 
Is this library removed from github or is it just a moving of address?

**Comment by DMaxwell02** [comment]
Yes. I have also noticed there is a broken link. I am looking for more help by way of helper classes on programmatically creating Azure Digital Twin Models but the task is made more difficult by this broken link.

**Comment by atx-barnes** [comment]
Any update on this? I see the NuGet library was updated about 4 months ago but haven't been able to find the source code anywhere.

**Comment by rido-min** [comment]
Hi @atx-barnes 

Yes, we are working to publish the DTDL parser source code, although we don't have an ETA yet. Will be great if you can share your use cases, and if needed we can give you access to the private repo.

LMK if you want to have a quick chat to better understand your scenario, you can reach out to rmpablos at microsoft dot com.

**Comment by thern743** [comment]
@rido-min 
I'm not the OP but we've had similar use cases where I've wanted to translate the DTDL parsing library to other languages (specifically NodeJS/Typescript). I'm building Angular-based tooling around around DTDL and I'd rather not have any dependencies on C#/.NET. That being said, if Microsoft would release a NodeJS/Typescript version of the DTDL parsing library that would suffice for my needs. Alternatively, a shared, public web API would also suffice.

**Comment by rido-min** [comment]
Hi @thern743 

We have released a new  DTDLParser https://github.com/digitaltwinconsortium/DTDLParser including a sample on how to consume it from JavaScript via WASM:  https://github.com/digitaltwinconsortium/DTDLParser/tree/main/samples/DTDLParserJSInteropSample

I'm very interested in your Angular tooling, is it available somewhere?

Also, happy to learn more about your scenarios. Would you like to spend 30 minutes in a call? (you can reach out to rmpablos at microsoft dot com)

**Comment by rido-min** [comment]
Hi @svenna , now that the [DTDLParser ](https://github.com/digitaltwinconsortium/DTDLParser) is open source, can you close this issue?

**Comment by svenna** [comment]
great news!
yeah i believe we can :)
