### ISSUE TITLE
Support arrays in property definitions

### ISSUE THREAD

**Issue by K2CanDo** [Azure/opendigitaltwins-dtdl#124]
The Plug and Play documentation states that the definition of arrays in properties is not supported yet (https://docs.microsoft.com/en-us/azure/iot-develop/concepts-modeling-guide).

Since it is now finally possible to have arrays in the device twin tough (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format), it should also be possible to define arrays in component properties.

**Comment by rido-min** [comment]
this is something we are targeting for DTDL v3. Stay tuned for upcoming updates.

**Comment by rido-min** [comment]
DTDL v3 has been published as preview, with support for arrays in properties.

Can you close this this issue?
