### ISSUE TITLE
Geospatial Schemas Documentation Coordinates order.

### ISSUE THREAD

**Issue by pandaGaume** [Azure/opendigitaltwins-dtdl#127]
Documentation state that Location based  informations are from GeoJson. 
Example from the Geospatial Schemas DTDL documentation is
```
{
    "location": {
        "type": "Point",
        "coordinates": [ 47.643742, -122.128014 ]
    }
}
```
This set coordinates as `[latitude, longitude]` (which is Microsoft building 16 at redmond) when [GeoJson ](https://geojson.org/)MUST be `[longitude, latitude]`.
Might be clarified in a way or another.

**Comment by rido-min** [comment]
@briancr-ms do you know the answer to this question?

**Comment by briancr-ms** [comment]
It's a bug in the example. I didn't read the GeoJSON spec closely enough to appreciate that the coordinate order is longitude, latitude before writing the example.

**Comment by rido-min** [comment]
@pandaGaume  thanks for the clarification, the sample has been updated and no longer indicates the sample geopoint referes to any specific location.

can you close this issue?

**Comment by pandaGaume** [comment]
thank's for the support
