### ISSUE TITLE
Validating Digital Twin updates against the Digital Twin model

### ISSUE THREAD

**Issue by EGitDeveloper** [Azure/opendigitaltwins-dtdl#129]
My apologies in advance if this is not correct place to ask the question.

In Azure IoT Central and Azure Digital Twin service, if I create and upload model with the following property:

```
{
    "@type": [ "Property", "Temperature" ],
    "name": "targetTemperature",
    "displayName": "Target Temperature",
    "unit": "degreeCelsius",
    "writable": true,
    ---> "schema": "double"
}
```
And I try to update writable property with string/boolean - update fails. 
```
[
  {
    "op": "replace",
    "path": "/targetTemperature",
    ---> "value":  "some value"
  }
]
```
Are there any specific libraries, SDKs or examples that I can use or reference to implement same kind of functionality in my application? That is, validate that updates conform with DTDL model.

**Comment by rido-min** [comment]
Well, the value should be a double, instead of `string/boolean`

Can you clarify which APIs/SDKs are you using for Central and ADT?

Central: https://docs.microsoft.com/en-us/rest/api/iotcentral/1.1-previewdataplane/devices/update-properties
ADT: https://docs.microsoft.com/en-us/rest/api/digital-twins/dataplane/twins/digitaltwins_update
https://github.com/Azure/azure-iot-sdk-node/blob/main/service/samples/javascript/update_digital_twin.js

**Comment by EGitDeveloper** [comment]
> Well, the value should be a double, instead of `string/boolean`
> 
> Can you clarify which APIs/SDKs are you using for Central and ADT?
> 
> Central: https://docs.microsoft.com/en-us/rest/api/iotcentral/1.1-previewdataplane/devices/update-properties ADT: https://docs.microsoft.com/en-us/rest/api/digital-twins/dataplane/twins/digitaltwins_update https://github.com/Azure/azure-iot-sdk-node/blob/main/service/samples/javascript/update_digital_twin.js

I'm working on my own API and solution that is neither based on IOT Central or Digital Twins service, however I'm using both of them as a reference/learning tool. That's why I'm wondering how I could design my solution to mimic IOT Central/Digital Twins service and refuse updates that break the DTDL model. 

To update DT or call commands I've used the [following examples](https://docs.microsoft.com/en-us/azure/iot-develop/concepts-developer-guide-service?pivots=programming-language-javascript#update-digital-twin).

Say my personal API has PATCH endpoint to update DT that accepts [PATCH body](https://docs.microsoft.com/en-us/rest/api/digital-twins/dataplane/twins/digitaltwins_update#update-a-digital-twin) - how do I validate PATCH request against DTDL model? "To update property on device with XYZ DTDL model you need to provide X type of a value, but you have provided Y, therefore you get BAD REQUEST response."

**Comment by EGitDeveloper** [comment]
That was basically it. I was researching Plug & Play Digital Twins and wondering if there's any public API/SDK that I can use to validate update payload against DTDL. Azure IOT Central and Digital Twins service both do it so I thought I might have missed documentation somewhere.

Thank you for clarification.

**Comment by rido-min** [comment]
Thanks for the feedback,

I will keep this issue open until we publish some validation APIs.

Thanks,
Rido

**Comment by rido-min** [comment]
Hi @EGitDeveloper 

Let me correct myself:

We have published a [preview parser](https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/6.1.0-preview) that *includes* a validation api, the following code snippet shows how to validate a payload.

```cs
var objectModel = new ModelParser().Parse(new string[] { ReadFile("geotypes-1.json") });

var rootInterface = (DTInterfaceInfo)objectModel[new Dtmi("dtmi:samplesv2:geoTypes;1")];

var myPoint = (DTTelemetryInfo)rootInterface.Contents["myPoint"];
var validPayload = myPoint.Schema.ValidateInstance(ToJs(new { type = "Point", coordinates = new double[] { 12.35, 23.56} }));
Console.WriteLine(validPayload);

var myGeopoint = (DTTelemetryInfo)rootInterface.Contents["myGeopoint"];
var validPayload2 = myGeopoint.Schema.ValidateInstance(ToJs(new { lat =12.35, lon = 23.56 }));
Console.WriteLine(validPayload2);
```

```json
{
    "@context": [
		"dtmi:dtdl:context;2",
		"dtmi:iotcentral:context;2"
	],
    "@id": "dtmi:samplesv2:geoTypes;1",
    "@type": "Interface",
    "contents": [
      {
        "@type": "Telemetry",
        "name": "myPoint",
        "schema": "point"
      },
      {
          "@type": ["Telemetry", "Location"],
          "name": "myGeopoint",
          "schema": "geopoint"
      }
    ]
  }
```
full gist is available [here](https://gist.github.com/rido-min/bb2afdd5dbf573100b107bbe0260b29d)

**Comment by EGitDeveloper** [comment]
Thank you for update! Looking forward to testing it out,

**Comment by rido-min** [comment]
closing due to lack of response
