### ISSUE TITLE
Add 'watthour' as a unit to the "Semantic type" energy 

### ISSUE THREAD

**Issue by mwdhont-auge** [Azure/opendigitaltwins-dtdl#139]
I'm missing the 'watthour' unit in the "semantic type" 'Energy'.
Is there any chance it can be added?

**Comment by lucasdietrich** [comment]
I'm also very interested in this addition.

**Comment by rido-min** [comment]
We are reviewing DTDL v3 with a revised [quantitativeTypes](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/Docs/en-US/DTDL.quantitativeTypes.v1.md) including `wattHour`.

If this is what you need, can you close this issue?

**Comment by mwdhont-auge** [comment]
Yes, thanks.
