### ISSUE TITLE
Using v2 and v3 contexts at the same time is valid

### ISSUE THREAD

**Issue by digimaun** [Azure/opendigitaltwins-dtdl#165]
Using the dtdlparser 1.0.48-preview, I noticed you are able to combine the v2 and v3 contexts at the same time. One thought around this, is by allowing mixed contexts it feels like it undermines at least one v3 extension which is [quantitativeTypes v1](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v3/DTDL.quantitativeTypes.v1.md).

Taking the first example off the quantitative types reference, removing the extension from @context causes an error as expected

![image](https://user-images.githubusercontent.com/28658112/233503984-3e20ed2c-ba37-43c4-82ee-36ce1079c00f.png)

However you can fix it by adding the v2 context, skipping usage of quantitative types altogether.

![image](https://user-images.githubusercontent.com/28658112/233504128-92420fc5-1a48-4c65-b925-4cbe2fbc56e7.png)

**Comment by jrdouceur** [comment]
The context rule in JSON-LD is that later contexts override earlier contexts.  So, your second example is actually DTDL v2.  It is not a combination of v3 and v2.  If you try to use a v3 feature (such as Array in Property) in your second example, it will fail with an error.

**Comment by digimaun** [comment]
Understood, thanks for explaining this JSON-LD rule.

Separate from the original issue, I also want to confirm that in DTDL v2, you are able to use unknown context specifiers where-as in v3 only known context specifiers are allowed right?

Here is example with v2 that is valid

![image](https://user-images.githubusercontent.com/28658112/233512383-82bfcb05-172b-40f8-9065-3a908d2d9801.png)

Which fails with v3

![image](https://user-images.githubusercontent.com/28658112/233512455-b5799a53-b17d-4ddf-bb8d-d615d0d600e6.png)

**Comment by digimaun** [comment]
Closing, will follow up on the additional question later.
