### ISSUE TITLE
How to define Telemetry/State and Telemetry/Event

### ISSUE THREAD

**Issue by matsujirushi** [Azure/opendigitaltwins-dtdl#34]
I created Device Template in IoT Central manually and export.
I see below:
```
            "@type": [
              "Telemetry",
              "SemanticType/Event"
            ],
```

But I cannot find information of SemanticType in DTDL.
Is this DTDL format correct?

**Comment by briancr-ms** [comment]
This is an IoT Central extension to DTDL. In DTDL v2, we have worked to consolidate most semantic types, which are listed in the DTDL v2 language spec.

The DTDL v2 parser will handle the above format when the DTDL v1 @context (http://azureiot.com/v1/contexts/IoTModel.json) is specified: https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/.
