### ISSUE TITLE
Can't create Azure PnP code stub if interface schema contains an array.

### ISSUE THREAD

**Issue by SteveMaz** [Azure/opendigitaltwins-dtdl#42]
Issue Type: Bug

Create an interface schema that contains the array sample shown below.

{
"@type": "Telemetry",
"name": "ledState",
"schema": {
"@type": "Array",
"elementSchema": "boolean"
}
}

Try to build the code stub for this. The following error is displayed:

[ERROR][PnPCodeGen] Failed to parse interface definition, @id: urn:................:.....................:1, error: Microsoft.Azure.IoT.DigitalTwin.Parser.ModelParserException: Content is not valid

Name=ledState:elementSchema, Id=Name, Description=Name is required
Name=ledState:elementSchema, Description=Schema should be provided

[IoT Plug and Play] generate PnP device code failed.

The same interface schema can be uploaded to Azure successfully.

VS Code version: Code 1.40.2 (f359dd6, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by dooriya** [comment]
Thanks for the feedback.

Currently we don't support the Array schema in CodeGen tool, so this is a feature requirement. If you feel that this feature is crucial, we are happy to listen and to reconsider to put it in our road-map.
