### ISSUE TITLE
Please better define "Developer" and "Human Readable"

### ISSUE THREAD

**Issue by askpatrickw** [Azure/opendigitaltwins-dtdl#45]
For the `comment` attribute it says "a Developer comment" and then for `description`, `displayName`, 'displayUnit' it says "A localizable name for human display."

Last I checked almost all developers were humans. Can you clarify these descriptions and can you elaborate on how these attribute values are used upstream in IoT Central, IoT Solution Accelertors, etc.. 

I believe the `description`, `displayName`, 'displayUnit' are surfaces to application users in IoT Central where as the `comment` is not an only meant to aid the DTDL author(s). Who may not be developers but also probably human. ;-)

Thanks!

**Comment by briancr-ms** [comment]
Fixed in #68.
