### ISSUE TITLE
It's valid an interface without contents?

### ISSUE THREAD

**Issue by rido-min** [Azure/opendigitaltwins-dtdl#64]
Given

```
{
    "@context": "dtmi:dtdl:context;2",
    "@id": "dtmi:com:m1;1",
    "@type": "Interface"
}
```
The parser reports it as valid
```
model size = 1
id=dtmi:com:m1;1 type=DTInterfaceInfo
JSON-LD text:
{
  "@context": [
    "dtmi:dtdl:context;2"
  ],
  "@id": "dtmi:com:m1;1",
  "@type": "Interface"
}
    property=IsPartition type=Boolean value=True (Boolean)
    property=EntityKind type=DTEntityKind value=Interface (DTEntityKind)
    property=Id type=Dtmi value=dtmi:com:m1;1 (Dtmi)
    property=LanguageVersion type=Int32 value=2 (Int32)
    property=IsPartition type=Boolean value=True (Boolean)
```

But uploading to the model repository fails

![image](https://user-images.githubusercontent.com/14916339/88424861-2f96d980-cda3-11ea-996c-3351050404a9.png)

/c @briancr-ms

**Comment by briancr-ms** [comment]
Yes, it's valid to have an interface definition without a `contents` property. This is described in the DTDL v2 language spec where the property `contents` is listed as optional: https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#interface.
