### ISSUE TITLE
Publish your contexts please :)

### ISSUE THREAD

**Issue by OR13** [Azure/opendigitaltwins-dtdl#65]
` "@context": "dtmi:dtdl:context;2",`

While this valid... its less helpful than a public URL.

I suggest publishing the context via github pages.

Without the context, these JSON-LD cannot be signed or compressed with semantic awareness.

**Comment by briancr-ms** [comment]
The context files for DTDL v2 are now available here: https://github.com/Azure/opendigitaltwins-dtdl/tree/master/DTDL/v2/context.
