### ISSUE TITLE
Add documentation for point, etc. schemas supported for telemetry

### ISSUE THREAD

**Issue by briancr-ms** [Azure/opendigitaltwins-dtdl#80]
DTDL v2 supports point, etc. (the GeoJSON geometry types) as schemas for telemetry. The documentation should be updated to include this with same examples.

**Comment by uriel-kluk** [comment]
@briancr-ms GeoJson coordinates are an array, and DTDL does not support for **properties**.
Some tools like IOTC or the PnP IoT Explorer allow you to select schema `point` but then it fails to save, import, export

is it expected to support GeoJson for Telemetry but not for Properties?

**Comment by briancr-ms** [comment]
Yes, in DTDL v2 all the geospatial types (point, etc.) are GeoJSON-based and can only be used in telemetry and commands (not properties). Separately, we are working on enabling arrays in properties in a future DTDL release.
