### ISSUE TITLE
The formal model of DTDL v2?

### ISSUE THREAD

**Issue by jbkoh** [Azure/opendigitaltwins-dtdl#84]
Hi there, thanks for sharing the great project! It's really awesome that Azure steps up to share what they model for digital twins! I am one of the lead developers of Brick Schema (brickschema.org) for buildings and trying to see if Brick can fit other meta-frameworks like DTDL. 

Is there any formal model of DTDLv2 that I can look into? I looked up the folder (https://github.com/Azure/opendigitaltwins-dtdl/tree/master/DTDL/v2) but only [a context file](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/context/DTDL.v2.context.json) is available. I'd be interested in how you model properties and constraints other than the markdown file. I expected to have a JSON-LD (possibly with SHACL Shapes as included in your context file) for example.

**Comment by rido-min** [comment]
this? https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/Metamodel/DTDL.v2.ModelRDF-SHACL.json

**Comment by jbkoh** [comment]
Yes. Thanks!
