### ISSUE TITLE
Update DTDL documentation to include JSON-LD details

### ISSUE THREAD

**Issue by briancr-ms** [Azure/opendigitaltwins-dtdl#86]
Every DTDL document is a JSON-LD document. The language spec alludes to this but does not contain information about how the terms used in the documentation map to JSON-LD (such as how the term "Interface" maps to a JSON-LD IRI). The suggestion is to add a section that focuses on DTDL and JSON-LD for readers interested in those details.

**Comment by rido-min** [comment]
We have updated the language docs with a better description of JSON-LD usage. I believe this issue can be closed.
