### ISSUE TITLE
Value of minMultiplicity

### ISSUE THREAD

**Issue by hellyzh** [Azure/opendigitaltwins-dtdl#87]
Value of minMultiplicity can only be set as 0 during public preview. Is there a plan to allow it be set as other number than 0 after GA since there is an [example](https://github.com/Azure/opendigitaltwins-dtdl/blob/6631b245d1d01986991a7d7e2cec15c2782527f7/DTDL/v2/dtdlv2.md#relationship-examples) showing it can be set as 1?

**Comment by briancr-ms** [comment]
Thanks for your question about minMultiplicity. For DTDL v2, minMultiplicity will be required to be set to 0. I will leave this issue active until we get a chance to update the docs.
