### ISSUE TITLE
Add unit Gauss for MagneticInduction

### ISSUE THREAD

**Issue by krwq** [Azure/opendigitaltwins-dtdl#95]
Would it be possible to add unit Gauss for MagneticInduction?

We currently have LSM9DS1 sensor (embedded on SenseHat) in https://github.com/dotnet/iot which provides MagneticInduction in Gauss but only available unit is Tesla.

**Comment by krwq** [comment]
Also for other units you can also check out what UnitsNet here: https://github.com/angularsen/UnitsNet/tree/master/UnitsNet/GeneratedCode/Units

**Comment by briancr-ms** [comment]
Thanks for your request. We're looking at enabling you to be able to add your own units (along with your own semantic types). I'll keep this issue open until we have a design to share.

**Comment by rido-min** [comment]
MagneticInduction with `gauss` and `tesla` units has been added to DTDL v3 quantitativeTypes
https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/Docs/en-US/DTDL.quantitativeTypes.v1.md
